spring.application.name=boot

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=web
spring.datasource.password=7898
spring.datasource.url=jdbc:mariadb://192.168.10.134:3306/care

# mybatis framework setting
mybatis.mapper-locations=/mappers/*.xml

# JSP settings
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

# file settings
spring.servlet.multipart.max-file-size=10MB

# server port settings
server.port=80