spring.application.name=zzaphub


#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.username=web
#spring.datasource.password=7898
#spring.datasource.url=jdbc:mariadb://192.168.10.134:3306/care

# --- Master DB 설정 (132번) ---
spring.datasource.master.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.master.jdbc-url=jdbc:mariadb://192.168.10.132:3306/care
spring.datasource.master.username=web
spring.datasource.master.password=7898

# --- Slave DB 설정 (152번) ---
spring.datasource.slave.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.slave.jdbc-url=jdbc:mariadb://192.168.10.152:3306/care
spring.datasource.slave.username=web
spring.datasource.slave.password=7898

# mybatis framework setting
mybatis.mapper-locations=/mappers/*.xml

# JSP settings
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

# file settings
spring.servlet.multipart.max-file-size=10MB

# server port settings
server.port=80